name: Deploy to Production Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          # Navigate to project directory
          cd /var/www/pdf-flow-reorder-magic
          
          # Pull latest changes
          git pull origin main
          
          # Install dependencies
          npm ci
          
          # Build the project
          npm run build
          
          # Copy built files to web server directory
          sudo cp -r dist/* /var/www/html/
          
          # Restart nginx (if using nginx)
          sudo systemctl reload nginx
          
          echo "Deployment completed successfully!"
